import { getPages } from '@/sanity/sanity-utlis';
import '../globals.css'
import Link from 'next/link';


export const metadata = {
  title: 'My Awesome Site',
  description: 'Generated by create next app',
}


export default async function RootLayout({children,}: {
  children: React.ReactNode
}) {
  const pages = await getPages();

  return (
    <html lang="en">
      <body className="max-w-3xl mx-auto py-10">
        <header>
          <Link href="/" className='bg-gray-100 rounded-lg text-gray-500 py-3 px-4 whitespace-nowrap hover:bg-pink-500 hover:text-pink-100 transition text-lg font-bold'>
            Ushie
          </Link>

          <div className="flex items-center text-sm gap-3">
              {pages.map((page) => (
                <Link key={page._id} href={`/${page.slug}`}>
                  {page.title}
                </Link>
              ))}
          </div>
        </header>

        <main className='mt-20'>
          {children}
        </main>
      </body>
    </html>  
  )
}
